version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8080:80
        networks:
            - symfony

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
        depends_on: 
            - db

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: sfUser
            MYSQL_PASSWORD: sfPassword
        volumes: 
            - ./mysql:/var/lib/mysql
        networks:
            - symfony
    
    phpmyadmin:
        image: phpmyadmin
        depends_on: 
            - db
        ports: 
            - 8081:80
        environment:
            PMA_HOST: db
        networks:
            - symfony

    maildev:
        image: djfarrelly/maildev
        ports: 
            - 8082:80
        networks:
            - symfony

networks:
    symfony: